### ISSUE TITLE
No module named contacts.api

### ISSUE THREAD

**Issue by malnafei** [smsapi/smsapi-contacts-python-client#1]
Hi,
i just install `smsapi-contacts==1.0.2` using pip without any error then i try to run my code but i get this error:

```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\github\smsapi\send.py", line 6, in <module>
    from contacts.api import ContactsApi
ImportError: No module named contacts.api
[Finished in 0.2s with exit code 1]
```

I know the problem come because there is no module named `contacts.api` but `smsapi-contacts` already installed.

Please, how to fix this.

**Comment by in-void** [comment]
Hi. 
Usage examples contains error, instead of writing 

`from contacts.api import ContactsApi`

You must use following syntax 

`from smsapicontacts.api import ContactsApi`

i fixed example in latest commit.

Thanks for your help.

**Comment by malnafei** [comment]
Thank you for your help.
Can you please try to use your example and test it to see if it's work or not because I still get another error with `Authorization failed` and I'm sure about my API username and password.

Error:

```
Traceback (most recent call last):
  File "C:\Users\users\Desktop\github\smsapi\send.py", line 11, in <module>
    contacts = api.list_contacts()
  File "C:\Python27\lib\site-packages\smsapi_contacts-1.0.2-py2.7.egg\smsapicontacts\endpoint.py", line 87, in __call
    return endpoint.send_request()
  File "C:\Python27\lib\site-packages\smsapi_contacts-1.0.2-py2.7.egg\smsapicontacts\endpoint.py", line 68, in send_request
    return self.process_response(raw_response)
  File "C:\Python27\lib\site-packages\smsapi_contacts-1.0.2-py2.7.egg\smsapicontacts\endpoint.py", line 75, in process_response
    raise ContactsApiError.from_dict(response)
smsapicontacts.exception.ContactsApiError:  Authorization failed
[Finished in 1.3s with exit code 1]
```

Also in Error handling change `from smsapi.exception import ContactsApiError` to `from smsapicontacts.exception import ContactsApiError` because `from smsapi.exception import ContactsApiError` not working.

**Comment by in-void** [comment]
At this momment You must provide your password in md5 format, try do something like this

```
import hashlib
from smsapicontacts.api import ContactsApi

m = hashlib.md5()
m.update('your-password')
password = m.hexdigest()

api = ContactsApi(username='your-username', password=password)
```

There is error in exceptions handling example and I will fix this in the nearest commit.

**Comment by malnafei** [comment]
I still get the same error here.

Here is my code:

```
import hashlib
from smsapicontacts.api import ContactsApi


m = hashlib.md5()
m.update('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
password = m.hexdigest()

api = ContactsApi(username='user@example.com', password=password)

contacts = api.list_contacts()
```

Error:

```
  File "C:\Python27\lib\site-packages\smsapi_contacts-1.0.2-py2.7.egg\smsapicontacts\endpoint.py", line 75, in process_response
    raise ContactsApiError.from_dict(response)
smsapicontacts.exception.ContactsApiError:  Authorization failed
```

**Comment by in-void** [comment]
ok, so now try in this way

```
import hashlib
from smsapicontacts.api import ContactsApi

m = hashlib.md5()
m.update('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
password = m.hexdigest()

api = ContactsApi(username='user@example.com', password=password)
api.host = 'https://api.smsapi.com/'

contacts = api.list_contacts()
```

**Comment by malnafei** [comment]
with the same error:
`smsapicontacts.exception.ContactsApiError:  Authorization failed`

Did you check it before you help me?

**Comment by in-void** [comment]
Yes i checked it. Please make sure that You provided correct API password which may be different than password to customer panel. You can set it here:  [https://ssl.smsapi.com/client_api/password](https://ssl.smsapi.com/client_api/password)

**Comment by malnafei** [comment]
I know that and i use the API password not my account cpanel password.
I try the API password with this code and everything works perfect:

	import requests
	url = 'https://api.smsapi.com/sms.do'
	payload = {'username': 'xxxxxx', 'password': 'xxxxxxxxxxxxxxxxxxxxx', 'from': 'Info', 'to': '968xxxxxxxxxx', 'message': 'This is a test'}

	# POST with form-encoded data
	r = requests.post(url, data=payload)

	# Response, status etc
	print r.text
	print r.status_code

The result:

	OK:1481132220532991110:0.03
	200
	[Finished in 1.2s]

You think the problem is because i set wrong API password in my code but i'm sure what i write.

Please check.

Thank you.
